export const APP_STARTED = 'APP_STARTED';
export const LOAD_APP_DATA_REQUEST = 'LOAD_APP_DATA_REQUEST';
export const LOAD_APP_DATA_SUCCESS = 'LOAD_APP_DATA_SUCCESS';
export const LOAD_APP_DATA_ERROR = 'LOAD_APP_DATA_ERROR';